from __future__ import annotations

from collections.abc import Mapping
from typing import Any

GENERATED_MARKER = "Generated by Agents Team. Do not edit directly."


def merge_dicts(base: dict[str, Any], override: Mapping[str, Any] | None) -> dict[str, Any]:
    if not override:
        return base

    result = dict(base)
    for key, value in override.items():
        if (
            key in result
            and isinstance(result[key], dict)
            and isinstance(value, Mapping)
        ):
            result[key] = merge_dicts(result[key], value)
        else:
            result[key] = value
    return result


def apply_prompt_override(body: str, override: Mapping[str, Any] | None) -> str:
    if not override:
        return body

    replacement = override.get("replace")
    if isinstance(replacement, str) and replacement.strip():
        return replacement.strip()

    prefix = override.get("prepend")
    suffix = override.get("append")
    parts: list[str] = []
    if isinstance(prefix, str) and prefix.strip():
        parts.append(prefix.strip())
    parts.append(body.strip())
    if isinstance(suffix, str) and suffix.strip():
        parts.append(suffix.strip())
    return "\n\n".join(parts)


def yaml_frontmatter(data: Mapping[str, Any]) -> str:
    import yaml

    return yaml.safe_dump(
        dict(data),
        sort_keys=False,
        allow_unicode=False,
        default_flow_style=False,
    ).strip()


def toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    return _toml_string(str(value))


def render_toml(data: Mapping[str, Any]) -> str:
    lines: list[str] = [f"# {GENERATED_MARKER}"]
    scalars: dict[str, Any] = {}
    tables: dict[str, Mapping[str, Any]] = {}

    for key, value in data.items():
        if isinstance(value, Mapping):
            tables[key] = value
        else:
            scalars[key] = value

    for key, value in scalars.items():
        if key == "developer_instructions":
            lines.append(f'{key} = """')
            lines.append(str(value).replace('"""', '\\"\\"\\"'))
            lines.append('"""')
        else:
            lines.append(f"{key} = {toml_value(value)}")

    for table_name, table_values in tables.items():
        lines.append("")
        lines.append(f"[{table_name}]")
        for key, value in table_values.items():
            lines.append(f"{key} = {toml_value(value)}")

    return "\n".join(lines).rstrip() + "\n"


def _toml_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\b", "\\b")
        .replace("\f", "\\f")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'

