from dataclasses import replace
from pathlib import Path

import yaml

from agents_team.parser import parse_agent_file
from agents_team.parser import load_agents
from agents_team.rendering import render_agent, render_root_agent


def test_renders_codex_toml() -> None:
    agent = parse_agent_file(Path("agents/raidel-auditor.md"))
    rendered = render_agent(agent, "codex")

    assert rendered.filename == "raidel-auditor.toml"
    assert 'name = "raidel-auditor"' in rendered.content
    assert 'sandbox_mode = "read-only"' in rendered.content
    assert "developer_instructions" in rendered.content
    assert "network_access" not in rendered.content


def test_renders_codex_root_agent_markdown() -> None:
    agents, issues = load_agents(Path("."))
    assert issues == []
    root = next(agent for agent in agents if agent.id == "raidel-planner")

    rendered = render_root_agent(root, agents, "codex")

    assert rendered.filename == "AGENTS.md"
    assert "Codex Root Planner" in rendered.content
    assert "You are the default planner" in rendered.content
    assert "Model preference: use `gpt-5.4`" in rendered.content
    assert "default request for orchestration" in rendered.content
    assert "`raidel-coder`" in rendered.content
    assert "`raidel-scout`" in rendered.content
    assert "`raidel-auditor`" in rendered.content
    assert "`raidel-researcher`" in rendered.content
    assert "`raidel-planner`" not in rendered.content


def test_renders_claude_root_agent_markdown() -> None:
    agents, issues = load_agents(Path("."))
    assert issues == []
    root = next(agent for agent in agents if agent.id == "raidel-planner")

    rendered = render_root_agent(root, agents, "claude")

    assert rendered.filename == "CLAUDE.md"
    assert "Claude Code Root Planner" in rendered.content
    assert "You are the default planner" in rendered.content
    assert "Model preference: use `opus`" in rendered.content
    assert "`.claude/agents/` are specialized subagents" in rendered.content
    assert "`raidel-coder`" in rendered.content
    assert "`raidel-scout`" in rendered.content
    assert "`raidel-auditor`" in rendered.content
    assert "`raidel-researcher`" in rendered.content
    assert "`raidel-planner`" not in rendered.content


def test_renders_claude_markdown() -> None:
    agent = parse_agent_file(Path("agents/raidel-auditor.md"))
    rendered = render_agent(agent, "claude")

    assert rendered.filename == "raidel-auditor.md"
    assert rendered.content.startswith("---\n# Generated by Agents Team")
    frontmatter = rendered.content.split("---", 2)[1]
    data = yaml.safe_load(frontmatter)
    assert data["name"] == "raidel-auditor"
    assert data["model"] == "sonnet"
    assert data["tools"] == "Read, Glob, Grep, Bash"
    assert set(data) == {"name", "description", "model", "tools"}


def test_renders_opencode_markdown() -> None:
    agent = parse_agent_file(Path("agents/raidel-researcher.md"))
    rendered = render_agent(agent, "opencode")

    assert rendered.filename == "raidel-researcher.md"
    assert rendered.content.startswith("---\n")
    frontmatter = rendered.content.split("---", 2)[1]
    data = yaml.safe_load(frontmatter)
    assert data["mode"] == "subagent"
    assert data["model"] == "openai/gpt-5.4-mini"
    assert data["permission"]["webfetch"] == "allow"
    assert "<!-- Generated by Agents Team. Do not edit directly. -->" in rendered.content


def test_renders_opencode_coding_agent_model() -> None:
    agent = parse_agent_file(Path("agents/raidel-auditor.md"))
    rendered = render_agent(agent, "opencode")

    frontmatter = rendered.content.split("---", 2)[1]
    data = yaml.safe_load(frontmatter)
    assert data["model"] == "openai/gpt-5.3-codex"


def test_renders_opencode_raidel_planner_as_primary_agent() -> None:
    agent = parse_agent_file(Path("agents/raidel-planner.md"))
    rendered = render_agent(agent, "opencode")

    assert rendered.filename == "raidel-planner.md"
    frontmatter = rendered.content.split("---", 2)[1]
    data = yaml.safe_load(frontmatter)
    assert data["mode"] == "primary"
    assert data["model"] == "openai/gpt-5.4"
    assert data["permission"]["task"] == {
        "*": "deny",
        "raidel-coder": "allow",
        "raidel-scout": "allow",
        "raidel-researcher": "allow",
        "raidel-auditor": "allow",
    }


def test_renders_opencode_agents_as_subagents_by_default() -> None:
    agent = parse_agent_file(Path("agents/raidel-auditor.md"))
    agent_without_override = replace(agent, overrides={})

    rendered = render_agent(agent_without_override, "opencode")

    frontmatter = rendered.content.split("---", 2)[1]
    data = yaml.safe_load(frontmatter)
    assert data["mode"] == "subagent"
