from pathlib import Path

from typer.testing import CliRunner

from agents_team.cli import app


runner = CliRunner()


def test_validate_prints_professional_success_summary() -> None:
    result = runner.invoke(app, ["validate"])

    assert result.exit_code == 0
    assert "Validation passed: 5 agent(s) ready." in result.output


def test_list_prints_agent_table() -> None:
    result = runner.invoke(app, ["list"])

    assert result.exit_code == 0
    assert "Canonical agents" in result.output
    assert "Agent" in result.output
    assert "Targets" in result.output
    assert "builder" in result.output


def test_render_without_out_keeps_raw_generated_content() -> None:
    result = runner.invoke(app, ["render", "codex", "reviewer"])

    assert result.exit_code == 0
    assert result.output.startswith("# Generated by Agents Team")
    assert "Rendered files" not in result.output


def test_render_with_out_prints_rendered_files_table(tmp_path: Path) -> None:
    result = runner.invoke(app, ["render", "codex", "reviewer", "--out", str(tmp_path)])

    assert result.exit_code == 0
    assert "Rendered files" in result.output
    assert "reviewer.toml" in result.output
    assert "Rendered 1 file(s)." in result.output
    assert (tmp_path / "codex" / "reviewer.toml").exists()


def test_doctor_prints_report_and_install_preview(tmp_path: Path) -> None:
    result = runner.invoke(app, ["doctor", "codex", "--project", str(tmp_path)])

    assert result.exit_code == 0
    assert "Doctor report" in result.output
    assert "Install preview" in result.output
    assert "install conflicts" in result.output


def test_install_dry_run_prints_operation_summary(tmp_path: Path) -> None:
    result = runner.invoke(app, ["install", "codex", "--project", str(tmp_path), "--dry-run"])

    assert result.exit_code == 0
    assert "Codex preview" in result.output
    assert "would-created" in result.output
    assert "Completed 5 operation(s): would-created: 5." in result.output
