from pathlib import Path

import yaml

from agents_team.parser import parse_agent_file
from agents_team.rendering import render_agent


def test_renders_codex_toml() -> None:
    agent = parse_agent_file(Path("agents/reviewer.md"))
    rendered = render_agent(agent, "codex")

    assert rendered.filename == "reviewer.toml"
    assert 'name = "reviewer"' in rendered.content
    assert 'sandbox_mode = "read-only"' in rendered.content
    assert "developer_instructions" in rendered.content


def test_renders_claude_markdown() -> None:
    agent = parse_agent_file(Path("agents/reviewer.md"))
    rendered = render_agent(agent, "claude")

    assert rendered.filename == "reviewer.md"
    assert rendered.content.startswith("<!-- Generated by Agents Team")
    frontmatter = rendered.content.split("---", 2)[1]
    data = yaml.safe_load(frontmatter)
    assert data["name"] == "reviewer"
    assert "Read" in data["tools"]
    assert "Write" in data["disallowedTools"]


def test_renders_opencode_markdown() -> None:
    agent = parse_agent_file(Path("agents/researcher.md"))
    rendered = render_agent(agent, "opencode")

    assert rendered.filename == "researcher.md"
    frontmatter = rendered.content.split("---", 2)[1]
    data = yaml.safe_load(frontmatter)
    assert data["mode"] == "subagent"
    assert data["permission"]["webfetch"] == "allow"

