from dataclasses import replace
from pathlib import Path

import yaml

from agents_team.parser import parse_agent_file
from agents_team.parser import load_agents
from agents_team.rendering import render_agent, render_root_agent


def test_renders_codex_toml() -> None:
    agent = parse_agent_file(Path("agents/reviewer.md"))
    rendered = render_agent(agent, "codex")

    assert rendered.filename == "reviewer.toml"
    assert 'name = "reviewer"' in rendered.content
    assert 'sandbox_mode = "read-only"' in rendered.content
    assert "developer_instructions" in rendered.content
    assert "network_access" not in rendered.content


def test_renders_codex_root_agent_markdown() -> None:
    agents, issues = load_agents(Path("."))
    assert issues == []
    root = next(agent for agent in agents if agent.id == "orchestrator")

    rendered = render_root_agent(root, agents, "codex")

    assert rendered.filename == "AGENTS.md"
    assert "Codex Root Orchestrator" in rendered.content
    assert "You are the default orchestrator" in rendered.content
    assert "default request for orchestration" in rendered.content
    assert "`builder`" in rendered.content
    assert "`explorer`" in rendered.content
    assert "`reviewer`" in rendered.content
    assert "`researcher`" in rendered.content


def test_renders_claude_markdown() -> None:
    agent = parse_agent_file(Path("agents/reviewer.md"))
    rendered = render_agent(agent, "claude")

    assert rendered.filename == "reviewer.md"
    assert rendered.content.startswith("<!-- Generated by Agents Team")
    frontmatter = rendered.content.split("---", 2)[1]
    data = yaml.safe_load(frontmatter)
    assert data["name"] == "reviewer"
    assert "Read" in data["tools"]
    assert "Write" in data["disallowedTools"]


def test_renders_opencode_markdown() -> None:
    agent = parse_agent_file(Path("agents/researcher.md"))
    rendered = render_agent(agent, "opencode")

    assert rendered.filename == "researcher.md"
    frontmatter = rendered.content.split("---", 2)[1]
    data = yaml.safe_load(frontmatter)
    assert data["mode"] == "subagent"
    assert data["model"] == "openai/gpt-5.4"
    assert data["permission"]["webfetch"] == "allow"


def test_renders_opencode_orchestrator_as_primary_agent() -> None:
    agent = parse_agent_file(Path("agents/orchestrator.md"))
    rendered = render_agent(agent, "opencode")

    assert rendered.filename == "orchestrator.md"
    frontmatter = rendered.content.split("---", 2)[1]
    data = yaml.safe_load(frontmatter)
    assert data["mode"] == "primary"
    assert data["model"] == "openai/gpt-5.4"
    assert data["permission"]["task"] == {"*": "deny"}


def test_renders_opencode_agents_as_subagents_by_default() -> None:
    agent = parse_agent_file(Path("agents/reviewer.md"))
    agent_without_override = replace(agent, overrides={})

    rendered = render_agent(agent_without_override, "opencode")

    frontmatter = rendered.content.split("---", 2)[1]
    data = yaml.safe_load(frontmatter)
    assert data["mode"] == "subagent"
