from __future__ import annotations

from pathlib import Path

import typer

from agents_team.diagnostics import build_doctor_report
from agents_team.installer import install_agents
from agents_team.rendering import render_agents, selected_tools
from agents_team.schema import ValidationIssue
from agents_team.validation import ensure_tool, has_errors, load_and_validate

app = typer.Typer(
    help="Install one canonical team of AI agents into Codex, Claude Code, and OpenCode."
)

@app.command("list")
def list_agents(root: Path = typer.Option(Path("."), "--root", resolve_path=True)) -> None:
    agents, issues = load_and_validate(root)
    _print_issues(issues, warnings_only=True)

    if not agents:
        typer.echo("No agents found.")
        raise typer.Exit(0)

    for agent in sorted(agents, key=lambda item: item.id):
        targets = ", ".join(tool for tool in selected_tools("all") if agent.enabled_for(tool))
        typer.echo(f"{agent.id}\t{targets}\t{agent.description}")


@app.command()
def validate(root: Path = typer.Option(Path("."), "--root", resolve_path=True)) -> None:
    agents, issues = load_and_validate(root)
    _print_issues(issues)

    if has_errors(issues):
        raise typer.Exit(1)

    typer.echo(f"Valid: {len(agents)} agent(s).")


@app.command()
def render(
    tool: str = typer.Argument(..., help="codex, claude, opencode, or all."),
    agent: str | None = typer.Argument(None, help="Optional agent id."),
    root: Path = typer.Option(Path("."), "--root", resolve_path=True),
    out: Path | None = typer.Option(
        None,
        "--out",
        help="Directory where generated files should be written.",
        file_okay=False,
        dir_okay=True,
        resolve_path=True,
    ),
) -> None:
    ensure_tool(tool)
    agents, issues = load_and_validate(root)
    _exit_if_invalid(issues)

    rendered = render_agents(agents, tool, agent)
    if agent and not rendered:
        typer.echo(f"Agent not found or not enabled for {tool}: {agent}", err=True)
        raise typer.Exit(1)

    if out:
        for item in rendered:
            target_dir = out / item.tool
            target_dir.mkdir(parents=True, exist_ok=True)
            target = target_dir / item.filename
            target.write_text(item.content, encoding="utf-8")
            typer.echo(f"rendered {item.tool}/{item.filename} -> {target}")
        return

    if len(rendered) != 1:
        typer.echo("Rendering multiple files requires --out.", err=True)
        raise typer.Exit(1)

    typer.echo(rendered[0].content, nl=False)


@app.command()
def install(
    tool: str = typer.Argument(..., help="codex, claude, opencode, or all."),
    root: Path = typer.Option(Path("."), "--root", resolve_path=True),
    project: Path | None = typer.Option(
        None,
        "--project",
        help="Install into a project-local agent directory instead of global.",
        file_okay=False,
        dir_okay=True,
        resolve_path=True,
    ),
    dry_run: bool = typer.Option(False, "--dry-run", help="Show planned writes only."),
    backup: bool = typer.Option(False, "--backup", help="Create backups before overwriting."),
    force: bool = typer.Option(False, "--force", help="Overwrite files not generated by Agents Team."),
) -> None:
    _install_or_update(tool, root, project, dry_run, backup, force)


@app.command()
def update(
    tool: str = typer.Argument(..., help="codex, claude, opencode, or all."),
    root: Path = typer.Option(Path("."), "--root", resolve_path=True),
    project: Path | None = typer.Option(
        None,
        "--project",
        help="Update a project-local installation instead of global.",
        file_okay=False,
        dir_okay=True,
        resolve_path=True,
    ),
    dry_run: bool = typer.Option(False, "--dry-run", help="Show planned writes only."),
    backup: bool = typer.Option(False, "--backup", help="Create backups before overwriting."),
    force: bool = typer.Option(False, "--force", help="Overwrite files not generated by Agents Team."),
) -> None:
    _install_or_update(tool, root, project, dry_run, backup, force)


@app.command()
def doctor(
    tool: str = typer.Argument("all", help="codex, claude, opencode, or all."),
    root: Path = typer.Option(Path("."), "--root", resolve_path=True),
    project: Path | None = typer.Option(
        None,
        "--project",
        help="Check a project-local installation target instead of global.",
        file_okay=False,
        dir_okay=True,
        resolve_path=True,
    ),
) -> None:
    report = build_doctor_report(root, tool, project)

    for check in report.checks:
        typer.echo(f"{check.status}: {check.label}: {check.detail}")

    _print_issues(report.validation_issues)

    if report.install_results:
        typer.echo("")
        typer.echo("Install preview:")
        for result in report.install_results:
            typer.echo(
                f"{result.action}: {result.rendered.tool}/{result.rendered.filename} -> {result.target_path}"
            )
            if result.message != "ok" and not result.message.startswith("dry"):
                typer.echo(f"  {result.message}")

    if report.has_errors:
        raise typer.Exit(1)


def _install_or_update(
    tool: str,
    root: Path,
    project: Path | None,
    dry_run: bool,
    backup: bool,
    force: bool,
) -> None:
    ensure_tool(tool)
    agents, issues = load_and_validate(root)
    _exit_if_invalid(issues)

    results = install_agents(
        agents,
        tool,
        project=project,
        dry_run=dry_run,
        backup=backup,
        force=force,
    )

    for result in results:
        typer.echo(
            f"{result.action}: {result.rendered.tool}/{result.rendered.filename} -> {result.target_path}"
        )
        if result.message != "ok" and not result.message.startswith("dry"):
            typer.echo(f"  {result.message}")


def _exit_if_invalid(issues: list[ValidationIssue]) -> None:
    _print_issues(issues)
    if has_errors(issues):
        raise typer.Exit(1)


def _print_issues(issues: list[ValidationIssue], warnings_only: bool = False) -> None:
    for issue in issues:
        if warnings_only and issue.level != "warning":
            continue
        location = f"{issue.file}: " if issue.file else ""
        typer.echo(f"{issue.level.upper()}: {location}{issue.message}", err=True)
