from __future__ import annotations

from datetime import datetime
from pathlib import Path

from agents_team.installers.common import GENERATED_MARKER
from agents_team.paths import install_dir, root_install_dir
from agents_team.rendering import find_agent, render_agents, render_root_agent, selected_tools
from agents_team.schema import Agent, InstallResult, RenderedFile


def install_rendered_file(
    rendered: RenderedFile,
    target_dir: Path,
    *,
    dry_run: bool = False,
    backup: bool = False,
    force: bool = False,
) -> InstallResult:
    target_path = target_dir / rendered.filename

    if target_path.exists():
        existing = target_path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in existing and existing.strip() and not force:
            return InstallResult(
                rendered=rendered,
                target_path=target_path,
                action="skipped",
                message="existing file is not generated by Agents Team; use --force to overwrite",
            )
        action = "updated"
    else:
        action = "created"

    if dry_run:
        return InstallResult(
            rendered=rendered,
            target_path=target_path,
            action=f"would-{action}",
            message="dry run",
        )

    target_dir.mkdir(parents=True, exist_ok=True)

    if backup and target_path.exists():
        backup_path = backup_file_path(target_path)
        backup_path.write_text(target_path.read_text(encoding="utf-8"), encoding="utf-8")

    target_path.write_text(rendered.content, encoding="utf-8")
    return InstallResult(
        rendered=rendered,
        target_path=target_path,
        action=action,
        message="ok",
    )


def install_agents(
    agents: list[Agent],
    tool: str,
    *,
    project: Path | None = None,
    dry_run: bool = False,
    backup: bool = False,
    force: bool = False,
    root_agent: str | None = None,
) -> list[InstallResult]:
    results: list[InstallResult] = []
    tools = selected_tools(tool)
    root_rendered: dict[str, RenderedFile] = {}
    if root_agent:
        root_tools = [
            selected_tool
            for selected_tool in tools
            if selected_tool in {"codex", "claude"}
        ]
        if not root_tools:
            raise ValueError("--root-agent is currently supported only for Codex and Claude installs")
        for selected_tool in root_tools:
            root = find_agent(agents, root_agent, selected_tool)
            root_rendered[selected_tool] = render_root_agent(root, agents, selected_tool)

    for selected_tool in tools:
        target_dir = install_dir(selected_tool, project)
        for rendered in render_agents(agents, selected_tool):
            if root_agent and selected_tool == "claude" and rendered.agent_id == root_agent:
                continue
            results.append(
                install_rendered_file(
                    rendered,
                    target_dir,
                    dry_run=dry_run,
                    backup=backup,
                    force=force,
                )
            )

    for selected_tool, selected_root_rendered in root_rendered.items():
        if selected_tool == "codex":
            codex_conflicts = [
                result
                for result in results
                if result.rendered.tool == "codex" and result.action == "skipped"
            ]
            root_target_dir = root_install_dir("codex", project)
            if codex_conflicts:
                results.append(
                    InstallResult(
                        rendered=selected_root_rendered,
                        target_path=root_target_dir / selected_root_rendered.filename,
                        action="skipped",
                        message="codex subagent conflicts must be resolved before writing root AGENTS.md",
                    )
                )
                continue

            results.append(
                install_rendered_file(
                    selected_root_rendered,
                    root_target_dir,
                    dry_run=dry_run,
                    backup=backup,
                    force=force,
                )
            )
            continue

        root_target_dir = root_install_dir(selected_tool, project)
        results.append(
            install_rendered_file(
                selected_root_rendered,
                root_target_dir,
                dry_run=dry_run,
                backup=backup,
                force=force,
            )
        )
    return results


def backup_file_path(path: Path) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    return path.with_name(f"{path.name}.{timestamp}.bak")
