from __future__ import annotations

from datetime import datetime
from pathlib import Path

from agents_team.installers.common import GENERATED_MARKER
from agents_team.paths import install_dir
from agents_team.rendering import render_agents, selected_tools
from agents_team.schema import Agent, InstallResult, RenderedFile


def install_rendered_file(
    rendered: RenderedFile,
    target_dir: Path,
    *,
    dry_run: bool = False,
    backup: bool = False,
    force: bool = False,
) -> InstallResult:
    target_path = target_dir / rendered.filename

    if target_path.exists():
        existing = target_path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in existing and not force:
            return InstallResult(
                rendered=rendered,
                target_path=target_path,
                action="skipped",
                message="existing file is not generated by Agents Team; use --force to overwrite",
            )
        action = "updated"
    else:
        action = "created"

    if dry_run:
        return InstallResult(
            rendered=rendered,
            target_path=target_path,
            action=f"would-{action}",
            message="dry run",
        )

    target_dir.mkdir(parents=True, exist_ok=True)

    if backup and target_path.exists():
        backup_path = backup_file_path(target_path)
        backup_path.write_text(target_path.read_text(encoding="utf-8"), encoding="utf-8")

    target_path.write_text(rendered.content, encoding="utf-8")
    return InstallResult(
        rendered=rendered,
        target_path=target_path,
        action=action,
        message="ok",
    )


def install_agents(
    agents: list[Agent],
    tool: str,
    *,
    project: Path | None = None,
    dry_run: bool = False,
    backup: bool = False,
    force: bool = False,
) -> list[InstallResult]:
    results: list[InstallResult] = []
    for selected_tool in selected_tools(tool):
        target_dir = install_dir(selected_tool, project)
        for rendered in render_agents(agents, selected_tool):
            results.append(
                install_rendered_file(
                    rendered,
                    target_dir,
                    dry_run=dry_run,
                    backup=backup,
                    force=force,
                )
            )
    return results


def backup_file_path(path: Path) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    return path.with_name(f"{path.name}.{timestamp}.bak")

